import type { ExposeeData } from "./ExposeeForm";

export interface DesignTemplate {
  id: string;
  name: string;
  description: string;
  primary: string;
  secondary: string;
  bg: string;
  text: string;
  accent: string;
  fontFamily: string;
  headerStyle: "gradient" | "image" | "minimal" | "bold" | "elegant";
  imageLayout: "alternating" | "grid" | "stacked" | "offset";
  factStyle: "cards" | "list" | "pills" | "minimal-row";
  sectionDivider: "accent-line" | "full-line" | "icon" | "none" | "dot";
  heroOverlay: "gradient-bottom" | "gradient-diagonal" | "vignette" | "solid-bar" | "none";
  cornerRadius: string;
  impressionImageSize: "large" | "medium";
}

export const designTemplates: DesignTemplate[] = [
  {
    id: "editorial",
    name: "The Editorial",
    description: "Magazin-Stil à la Architectural Digest",
    primary: "#1a1a1a",
    secondary: "#f5f2ed",
    bg: "#faf8f5",
    text: "#1a1a1a",
    accent: "#7c8c6e",
    fontFamily: "'Playfair Display', serif",
    headerStyle: "image",
    imageLayout: "offset",
    factStyle: "list",
    sectionDivider: "none",
    heroOverlay: "gradient-bottom",
    cornerRadius: "4px",
    impressionImageSize: "large",
  },
  {
    id: "modern-minimalist",
    name: "Modern Minimalist",
    description: "Bauhaus-inspiriert, Form follows Function",
    primary: "#2563eb",
    secondary: "#f3f4f6",
    bg: "#ffffff",
    text: "#111827",
    accent: "#3b82f6",
    fontFamily: "'Inter', sans-serif",
    headerStyle: "minimal",
    imageLayout: "grid",
    factStyle: "minimal-row",
    sectionDivider: "full-line",
    heroOverlay: "none",
    cornerRadius: "0px",
    impressionImageSize: "medium",
  },
  {
    id: "dark-prestige",
    name: "Dark Mode Prestige",
    description: "Luxuriös auf dunklem Grund",
    primary: "#1e293b",
    secondary: "#1a2332",
    bg: "#0f172a",
    text: "#f1f5f9",
    accent: "#c9a96e",
    fontFamily: "'Inter', sans-serif",
    headerStyle: "elegant",
    imageLayout: "stacked",
    factStyle: "cards",
    sectionDivider: "accent-line",
    heroOverlay: "vignette",
    cornerRadius: "8px",
    impressionImageSize: "large",
  },
  {
    id: "organic-scandi",
    name: "Organic Scandi",
    description: "Warm, einladend & hygge",
    primary: "#6b4f3a",
    secondary: "#f5ebe0",
    bg: "#fefcf8",
    text: "#3d2e22",
    accent: "#c4704b",
    fontFamily: "'Inter', sans-serif",
    headerStyle: "image",
    imageLayout: "alternating",
    factStyle: "pills",
    sectionDivider: "dot",
    heroOverlay: "gradient-bottom",
    cornerRadius: "20px",
    impressionImageSize: "large",
  },
  {
    id: "corporate-luxury",
    name: "Corporate Luxury",
    description: "Seriös & Investment-Optik",
    primary: "#1e3a5f",
    secondary: "#eef2f7",
    bg: "#ffffff",
    text: "#1a1a2e",
    accent: "#94a3b8",
    fontFamily: "'Inter', sans-serif",
    headerStyle: "gradient",
    imageLayout: "grid",
    factStyle: "cards",
    sectionDivider: "full-line",
    heroOverlay: "solid-bar",
    cornerRadius: "6px",
    impressionImageSize: "medium",
  },
  {
    id: "gallery",
    name: "The Gallery",
    description: "Ausstellungs-Look, Immobilie als Kunstwerk",
    primary: "#9ca3af",
    secondary: "#fafafa",
    bg: "#ffffff",
    text: "#6b7280",
    accent: "#d1d5db",
    fontFamily: "'Inter', sans-serif",
    headerStyle: "minimal",
    imageLayout: "stacked",
    factStyle: "minimal-row",
    sectionDivider: "none",
    heroOverlay: "none",
    cornerRadius: "0px",
    impressionImageSize: "large",
  },
  {
    id: "typographic-hero",
    name: "Typographic Hero",
    description: "Laut, urban & selbstbewusst",
    primary: "#111111",
    secondary: "#f5f5f5",
    bg: "#ffffff",
    text: "#111111",
    accent: "#ff5722",
    fontFamily: "'Inter', sans-serif",
    headerStyle: "bold",
    imageLayout: "offset",
    factStyle: "pills",
    sectionDivider: "accent-line",
    heroOverlay: "gradient-diagonal",
    cornerRadius: "0px",
    impressionImageSize: "large",
  },
  {
    id: "heritage-estate",
    name: "Heritage Estate",
    description: "Klassische Tradition & Beständigkeit",
    primary: "#5c1a1a",
    secondary: "#f8f4ef",
    bg: "#faf7f2",
    text: "#2c1810",
    accent: "#8b2e2e",
    fontFamily: "'Georgia', serif",
    headerStyle: "elegant",
    imageLayout: "alternating",
    factStyle: "list",
    sectionDivider: "dot",
    heroOverlay: "vignette",
    cornerRadius: "2px",
    impressionImageSize: "large",
  },
  {
    id: "glassmorphism",
    name: "Web 3.0 Glass",
    description: "Futuristisch & fließend",
    primary: "#6366f1",
    secondary: "#ede9fe",
    bg: "#f5f3ff",
    text: "#1e1b4b",
    accent: "#8b5cf6",
    fontFamily: "'Inter', sans-serif",
    headerStyle: "gradient",
    imageLayout: "grid",
    factStyle: "cards",
    sectionDivider: "none",
    heroOverlay: "gradient-diagonal",
    cornerRadius: "16px",
    impressionImageSize: "medium",
  },
  {
    id: "lifestyle-storyteller",
    name: "Lifestyle Storyteller",
    description: "Emotional & magazinartig",
    primary: "#374151",
    secondary: "#f9fafb",
    bg: "#ffffff",
    text: "#1f2937",
    accent: "#059669",
    fontFamily: "'Georgia', serif",
    headerStyle: "image",
    imageLayout: "offset",
    factStyle: "list",
    sectionDivider: "icon",
    heroOverlay: "gradient-bottom",
    cornerRadius: "12px",
    impressionImageSize: "large",
  },
];
